### PR TITLE
Add multiple versions of run icon for light and dark themes

### PR DESCRIPTION
**Pull request by JeffreyCA**
I've made 3 different run icons that match with different types of themes.

- `run-dark.png` goes well with dark themes (hence lighter color)

- `run-light.png` goes well with light themes (hence darker color)

- `run-color.png` is improves on old color, I just made it uniform in color and slightly changed the shade of green.

- `run-orig.png` is the old icon.

I changed `package.json` to use `run-color.png` by default. I'm not sure how to make the icon color change depending on the current user theme or preference.

### CODE REVIEW

**Comment by JeffreyCA** [comment]
Addresses #132.

**Comment by formulahendry** [comment]
For switching between different themes, you could refer to: https://github.com/formulahendry/vscode-docker-explorer/blob/master/package.json#L49
For the light & dark icon, could your share the screenshot?

**Comment by JeffreyCA** [comment]
Sure, here they are:

dark
light

Thanks, I will look into that.

**Comment by formulahendry** [comment]
Thanks!

**Pull request merged**
