### PR TITLE
Closes #30: Added basic support for compiled languages such as Java

### LINKED ISSUE #30: Add support for compiled language
Java, C++, Ocaml, etc.

### PR DESCRIPTION
**Pull request by manoelcampos**
- Added the new configurations below in package.json file to enable compiling and running Java and C files
   - "java": "cd $dir && javac $fileName && java $fileNameWithoutExt"
   -  "c": "gcc $fullFileName && ./a.out"
- Such configurations use some new placeholders (variables) that will be replaced
  by actual values. The introduced placeholders that can be used to compose commands
  to compile and run a given source file are:
  - $dir: replaced by the directory of the code file being run
  - $fullFileName: replaced by the full name of the code file being run
  - $fileName: replaced by the base name of the code file being run, that is the file without the directory
  - $fileNameWithoutExt: replaced by the base name of the code file being run without its extension
- Previous commands such as "python", in which the code file name will just be appended to the end of the command, continue to work as before.
- With these new placeholders, enabling the compilation and execution of other languages is just a matter of providing the correct command.

### CODE REVIEW

**Comment by formulahendry** [comment]
Thanks @manoelcampos ! It is sooooo cool!

**Comment by manoelcampos** [comment]
You're welcome. Thank you too for the awesome plugin 😄 . Please, tell me when the new version is available at Marketplace.

**Comment by formulahendry** [comment]
The new version is released in Marketplace now. Please have a try. Thanks again! 😃

**Comment by manoelcampos** [comment]
I've just installed 👍 😄

**Pull request merged**
