### PR TITLE
Add stop button in editor title bar

### PR DESCRIPTION
**Pull request by ChapC**
Adds a "Stop code run" button in the editor title bar that appears when code is running.

The button can be turned off with the configuration option "code-runner.showStopIconInEditorTitleMenu", which is set to True by default.

### CODE REVIEW

**Review by formulahendry — APPROVED** [review]
:shipit:

**Comment by j0k4rX** [comment]
the stop button looks funny on windows 😂
can't really differ from these two
1. small square
2. big square

Screenshot 2021-07-10 203311

**Comment by ChapC** [comment]
You mean the maximize window button? I developed this on Windows and wasn't phased by it, but I see what you mean.

The square is a pretty universal stop button as far as know, so I'm not sure what we would change it to. An "X" could work but then that looks just like the close window button.

Any suggestions for an alternative icon?

**Comment by j0k4rX** [comment]
unfortunately, i don't have

**Pull request merged**
